// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoServices.Domain;

namespace TodoServices.Domain.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20181221124646_ChangeTodoTable")]
    partial class ChangeTodoTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Todo")
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TodoServices.Domain.Model.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<decimal?>("ChildCost")
                        .HasColumnType("smallmoney");

                    b.Property<DateTime?>("CompleteDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("smallmoney");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("smallmoney");

                    b.Property<int?>("ParentId");

                    b.Property<int?>("PerformerId");

                    b.Property<byte>("Priority");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(16);

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ParentId");

                    b.HasIndex("PerformerId");

                    b.HasIndex("Priority", "CreateDate", "CompleteDate");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("TodoServices.Domain.Model.Todo", b =>
                {
                    b.HasOne("TodoServices.Domain.Model.Todo", "Parent")
                        .WithMany("Childs")
                        .HasForeignKey("ParentId");
                });
#pragma warning restore 612, 618
        }
    }
}
